language: scala

scala:
   - 2.12.3

script:
   - sbt ++$TRAVIS_SCALA_VERSION test

cache:
  # These directories are cached at the end of the build
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
